USE [admin-db]
WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'))
BEGIN
    DECLARE @action NVARCHAR(2000)
    SELECT  TOP 1 @action = ('ALTER TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME + '] DROP CONSTRAINT [' + CONSTRAINT_NAME + ']')
    FROM    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE   CONSTRAINT_TYPE = 'FOREIGN KEY'
    EXEC (@action)
END
EXEC sp_MSForEachTable 'TRUNCATE TABLE ?'
GO
USE [master]